#! /bin/bash

# define colors
C_DEFAULT="\[\033[m\]"
C_WHITE="\[\033[1m\]"
C_BLACK="\[\033[30m\]"
C_RED="\[\033[31m\]"
C_GREEN="\[\033[32m\]"
C_YELLOW="\[\033[33m\]"
C_BLUE="\[\033[34m\]"
C_PURPLE="\[\033[35m\]"
C_CYAN="\[\033[36m\]"
C_LIGHTGRAY="\[\033[37m\]"
C_DARKGRAY="\[\033[1;30m\]"
C_LIGHTRED="\[\033[1;31m\]"
C_LIGHTGREEN="\[\033[1;32m\]"
C_LIGHTYELLOW="\[\033[1;33m\]"
C_LIGHTBLUE="\[\033[1;34m\]"
C_LIGHTPURPLE="\[\033[1;35m\]"
C_LIGHTCYAN="\[\033[1;36m\]"
C_BG_BLACK="\[\033[40m\]"
C_BG_RED="\[\033[41m\]"
C_BG_GREEN="\[\033[42m\]"
C_BG_YELLOW="\[\033[43m\]"
C_BG_BLUE="\[\033[44m\]"
C_BG_PURPLE="\[\033[45m\]"
C_BG_CYAN="\[\033[46m\]"
C_BG_LIGHTGRAY="\[\033[47m\]"


color_dir=~/.local/color_num.txt
if [ `which $color_dir` ] ; then
	color_num=`cat $color_dir`
	echo `expr $color_num + 1` > $color_dir
else
	touch $color_dir
	chmod +x $color_dir
	echo 1 > $color_dir
	color_num=1
fi

#colorset=($C_DEFAULT $C_WHITE $C_RED $C_GREEN $C_YELLOW $C_BLUE $C_PURPLE $C_CYAN $C_LIGHTGRAY $C_DARKGRAY $C_LIGHTRED $C_LIGHTGREEN $C_LIGHTYELLOW $C_LIGHTBLUE $C_LIGHTPURPLE $C_LIGHTCYAN )
colorset=(
$C_DARKGRAY 
$C_LIGHTGRAY 
$C_WHITE 
$C_LIGHTRED 
$C_RED 
$C_LIGHTPURPLE 
$C_PURPLE 
$C_LIGHTYELLOW 
$C_YELLOW 
$C_LIGHTGREEN 
$C_GREEN 
$C_LIGHTBLUE 
$C_BLUE 
$C_LIGHTCYAN 
$C_CYAN
)


#export PS1="$C_LIGHTYELLOW\h:$C_LIGHTGREEN\W \$$C_DEFAULT "
#PS1='${debian_chroot:+($debian_chroot)}\[\033[01;33m\]\u\[\033[35m\]@\[\033[36m\]\[\033[00m\]:\[\033[01;31m\][\A]\[\033[34m\]\W\[\033[35m\]\$ \[\033[00m\]'

 PS1="${colorset[$color_num]}${debian_chroot:+($debian_chroot)}\u\[\033[35m\]@\[\033[36m\]\[\033[00m\]:\[\033[01;31m\][\A]\[\033[34m\]\W\[\033[35m\]\$ \[\033[00m\]"

if [ $color_num -eq 15 ] ; then
	color_num=0
	echo 0 > $color_dir
fi

